### ISSUE TITLE
Translation char Č at begin of string

### ISSUE THREAD

**Issue by Fires04** [FrSky-OS/X12S-bug-report#47] opened 2016-12-10 19:32 UTC
Hi, I maked translation FrskyOS to Czech language. But I found bug. If is the first char in string = Č - czech char, that char is not displayed in OS. If the char Č is somwhere in string it is no problem. 

![dsc_0317](https://cloud.githubusercontent.com/assets/699214/21075670/f366bc2a-bf17-11e6-9b67-d803840a245a.jpg)
![dsc_0316](https://cloud.githubusercontent.com/assets/699214/21075669/f366b126-bf17-11e6-8131-a09aecb25b59.jpg)

**Comment by janekx** [comment] 2016-12-12 07:32
Know issue, will be fixed in new public FW with localisation

**Comment by janekx** [comment] 2016-12-12 07:47
bad button

**Comment by Adelaxie** [comment] 2016-12-12 08:15
For now, we think it is caused by .csv file generated by different kinds of softwares.
We engineer likes to test with txt editor and always has no issue.
So which software do you use?
can you try to use txt editor to make sure of it as well?

**Comment by Fires04** [comment] 2016-12-12 08:18
Hi,  i used google docs.   I will try different editor.

Dne 12. 12. 2016 9:15 dopoledne napsal uživatel "Adela" <
notifications@github.com>:

**Comment by Adelaxie** [comment] 2016-12-13 02:02
Please test latest firmware here.
http://221.228.240.132:8001/Adela/.horus_localisation1212.zip

Note:Please remove the _1212 in the tail of the file name.

**Comment by Adelaxie** [comment] 2016-12-28 00:40
L version fixed the issue .

**Closed by Adelaxie** 2016-12-28 00:40 UTC
Labels: bug low, Fixed Already
